### ISSUE TITLE
Questions on how to use the lazyloader middleware

### ISSUE THREAD

**Issue by tobiasdiez** [gajus/graphql-lazyloader#4]
First of all, thanks a lot for creating this middleware. I just read the article by the Paypal team and hesitate to use it due to the boilerplate - so exactly the motivation for your work.

I have two questions how to use the lazyloader middleware correctly:
1. How do you specify which fields should trigger the load and which not.
For example, consider the following example (slight extension of the one in the readme):
```graphql
type Person {
    id: ID!
    givenName: String!
    familyName: String!
    fullName: String!
    positions: [String!]
}
```
with resolvers 
```js
Person: {
  fullName: ({givenName, familyName}) => givenName + " " + familyName
  positions: ({id}) => getPositions(id)
}
```
where `getPositions` accesses eg the database. And lazyloader:
```js
const lazyLoadMiddleware = createLazyLoadMiddleware({
  Person: ({id}) => {
    return getPerson(id);
  },
});
```
As can be seen above, the `fullName` resolver needs a fully resolved `person` object (i.e should call `getPerson`), while `positions` doesn't need the persons object (only its id) and thus shouldn't trigger `getPerson`. How can this specified in the middleware?

2. How are null values handled?
In the context of the example in the readme, resolving the query `person(id)` for an id that doesn't exist should return null at the root level (and not an person object with null givenName). How can this be achieved?

**Comment by gajus** [comment]
Are these questions not covered by [test cases](https://github.com/gajus/graphql-lazyloader/blob/master/test/graphql-lazyloader/createLazyLoadMiddleware.ts)?

If they are not, please contribute a test case that demonstrates what you wish to achieve vs what is happening. Otherwise, it is really hard to figure out what someone is asking without having expected / actual code.

**Comment by tobiasdiez** [comment]
Ok, I've created a pull request for each question.
